[project]
name = "simplejpeg"
description = "A simple package for fast JPEG encoding and decoding."
readme = "README.rst"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
]
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "Joachim Folz", email = "joachim.folz@dfki.de" }]
keywords = [
    "the",
    "fastest",
    "JPEG",
    "encoding",
    "decoding",
    "package",
    "in",
    "town",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/jfolz/simplejpeg/blob/master/README.rst"
Source = "https://github.com/jfolz/simplejpeg"
Tracker = "https://github.com/jfolz/simplejpeg/issues"

[project.optional-dependencies]
numpy = ["numpy>=1.19.3"]
dev = [
    "numpy>=1.19.3",
    "Pillow>=7.0.0",
    "pytest>=5.3.2",
]

[build-system]
requires = [
    "setuptools>=77.0.0",
    "wheel",
    "cython>=3.3,<4",
]
backend-path = ["custom_build_backend"]
build-backend = "custom_build_meta"

[tool.cibuildwheel]
environment = { PIP_ONLY_BINARY=':all:' }
skip = "cp3[1-9][0-9]t-* *_i686 *musllinux* *-win32 cp39-win_arm64 cp310-win_arm64"
build-verbosity = 1
test-requires = "pytest>=5.3.2 numpy Pillow>=7.0.0"
test-command = "pytest {project}/test -vv"

[tool.cibuildwheel.linux]
before-all = "dnf install -y nasm"

[tool.cibuildwheel.macos]
before-all = "brew install nasm"

[tool.cibuildwheel.windows]
before-all = "choco install nasm -y --no-progress"
