name: Build

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: macos-15-intel
            arch: x86_64
          - os: macos-latest
            arch: aarch64
          - os: windows-latest
            arch: x86_64
          - os: windows-11-arm
            arch: aarch64
    steps:
      - uses: actions/checkout@v5
      - name: Set up MSVC
        if: runner.os == 'Windows' && matrix.arch != 'aarch64'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up MSVC
        if: runner.os == 'Windows' && matrix.arch == 'aarch64'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64
      - name: Wait for docker to wake up on ARM
        if: runner.os == 'Linux' && matrix.arch == 'aarch64'
        run: while ! docker version; do sleep 1; done
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD: cp39-* cp310-* cp311-*
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build SDist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error
  upload_all:
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true
      - name: Create Github release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: dist/*
          draft: false
          prerelease: false
